title: Ian Jiang's Portfolio
description: I dont have short description haha.
theme: jekyll-theme-minimal

# Optional settings
show_downloads: false

# To use remote themes
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-sass-converter

# Additional optional configurations
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"